# Generated by Django 3.2.9 on 2021-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dssp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=200, verbose_name='PDB name')),
                ('dssp_content', models.TextField(verbose_name='full DSSP context')),
                ('count_date', models.DateTimeField(verbose_name='count date')),
            ],
        ),
        migrations.CreateModel(
            name='DsspCalcResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
